### ISSUE TITLE
My accuracy is low. Which dataset did you use?

### ISSUE THREAD

**Issue by krnlyng** [zingmars/vocal-music-separation#2] opened 2022-02-21 18:57 UTC
I am using DSD100, but it seems i cannot get the accuracy higher than 0.01. Did you use a bigger dataset?

The outcome is that the vocals.wav file is completely empty. (At some point when i messed with some parameters i had even lower accuracy and the vocals.wav contained recognizeable song parts).

Also newer versions of librosa don't support librosa.output.write_wav anymore it seems. I used soundfile as a replacement.

**Comment by zingmars** [comment] 2023-04-29 20:33
wow, Github did not notify me about this comment at all. That's a shame.

I'm not sure about how relevant these questions are anymore, but I'll answer anyway.
In regards to datasets, I used parts from all of the datasets listed [here](https://github.com/zingmars/vocal-music-separation#example-data-sets). In total I used 106 full songs for training, and 45 for validation. I got roughly 98% accuracy which while sounds high, still resulted in fairly noisy output. In some very rare cases you could get clean vocals, but in most cases you would get outputs with some slight background noise from the instruments.

Not quite sure why it wouldn't work for you, but seeing as you had issues with some of the libraries, my guess is that some functionality of other libraries also might have been broken in time. My recommendation would be to set up python venv and install the specific libraries mentioned in the requirements file.

Since this issue is over a year old, I'm going to assume that the problem is no longer relevant and I'll close this issue. In case it still is, feel free to re-open.

**Closed as completed by zingmars** 2023-04-29 20:33 UTC
